### ISSUE TITLE
permanent community-call repo to facilitate following project updates

### ISSUE THREAD

**Issue by mewmew** [eliasnaur/community-call-dec-2020#1]
Hi Elias, Christopher and everyone else involved in Gio.

I was glad to join the video chat for the last community call, even if I missed the beginning of it.

I'd like to ask if it be possible to rename this repo from `community-call-dec-2020` to `community-call` and have it be a permanent repository for slides of Gio community calls. This would facilitate following project updates (as it enables watching the repo for changes).

I'm very excited to follow Gio development, but have yet to find a good way of doing so. As I'm not a frequent user of mailing lists, the main communication channel of Gio is made inaccessible to me. And, as the main project is hosted on Sourcehut, there is no simple way for me to follow updates (e.g. new issues created, PRs merged, etc).

I know this boils down to personal preference of development tools used, so consider this a data point from a user and Go developer who would like to keep up-to-date with the Gio project, but is currently lacking channels for it.

Wish you all the best and a good winter vacation!

Cheers,
Robin

**Comment by eliasnaur** [comment]
Good idea, I've renamed the repository.

If you don't know about them already, you can follow the [Gio YouTube channel](https://www.youtube.com/channel/UCzuKUnKK5gAFJKNyA1imIHw) for call recordings, and [@gioui on Twitter](https://twitter.com/giouiorg). I post the recordings and newsletters on Twitter, and particularly the newsletters are a great way to be updated on new development.

**Comment by mewmew** [comment]
> If you don't know about them already, you can follow the Gio YouTube channel for call recordings, and @gioui on Twitter. I post the recordings and newsletters on Twitter, and particularly the newsletters are a great way to be updated on new development.

Thanks! I really enjoy the new letters as they are very informative! I've also been watching the YouTube channel. The last community call was four months ago, so therefore I went to check the mailing list and just happened to time the real-time community call the other day, by pure luck.

Don't have Twitter myself, but I'm sure others find that channel useful too.

Cheers,
Robin
